# Base MSSQL image
FROM mcr.microsoft.com/mssql/server:2022-latest

# Set dir and copy there
WORKDIR /usr/src/app
COPY db-entrypoint.sh .
COPY db-init.sql .

# Run entrypoint script to start mssql and then run init script for setup
CMD ["/bin/bash", "./db-entrypoint.sh"]
