services:
  rekurrens-frontend:
    image: registry.chasacademy.dev/chas-challenge-2025/group-12/rekurrens/react:${DOCKER_TAG}
    networks:
      - rekurrens-network
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${STACK_NAME}-http.rule=Host(`${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.${STACK_NAME}-http.entrypoints=http
        - traefik.http.routers.${STACK_NAME}-http.middlewares=https-redirect
        - traefik.http.routers.${STACK_NAME}-https.rule=Host(`${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.${STACK_NAME}-https.entrypoints=https
        - traefik.http.routers.${STACK_NAME}-https.tls=true
        - traefik.http.routers.${STACK_NAME}-https.tls.certresolver=le
        - traefik.http.routers.<DIN-HTTPS-ROUTER>.tls.domains[0].main=cc25.chasacademy.dev
        - traefik.http.routers.<DIN-HTTPS-ROUTER>.tls.domains[0].sans=*.cc25.chasacademy.dev
        - traefik.http.services.${STACK_NAME}.loadbalancer.server.port=80
    environment:
      - API_URL=http://rekurrens-backend:80

  rekurrens-backend:
    image: registry.chasacademy.dev/chas-challenge-2025/group-12/rekurrens/dotnet:${DOCKER_TAG}
    networks:
      - rekurrens-network
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.api-${STACK_NAME}-http.rule=Host(`api.${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.api-${STACK_NAME}-http.entrypoints=http
        - traefik.http.routers.api-${STACK_NAME}-http.middlewares=https-redirect
        - traefik.http.routers.api-${STACK_NAME}-https.rule=Host(`api.${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.api-${STACK_NAME}-https.entrypoints=https
        - traefik.http.routers.api-${STACK_NAME}-https.tls=true
        - traefik.http.routers.api-${STACK_NAME}-https.tls.certresolver=le
        - traefik.http.routers.<DIN-HTTPS-ROUTER>.tls.domains[0].main=cc25.chasacademy.dev
        - traefik.http.routers.<DIN-HTTPS-ROUTER>.tls.domains[0].sans=*.cc25.chasacademy.dev
        - traefik.http.services.api-${STACK_NAME}.loadbalancer.server.port=80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=rekurrens-db;Database=Rekurrens;User=sa;Password=${DB_PASSWORD};TrustServerCertificate=True
    depends_on:
      - rekurrens-db

  adminer:
    image: adminer:latest
    networks:
      - rekurrens-network
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.db-${STACK_NAME}-http.rule=Host(`db.${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.db-${STACK_NAME}-http.entrypoints=http
        - traefik.http.routers.db-${STACK_NAME}-http.middlewares=https-redirect
        - traefik.http.routers.db-${STACK_NAME}-https.rule=Host(`db.${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.db-${STACK_NAME}-https.entrypoints=https
        - traefik.http.routers.db-${STACK_NAME}-https.tls=true
        - traefik.http.routers.db-${STACK_NAME}-https.tls.certresolver=le
        - traefik.http.routers.<DIN-HTTPS-ROUTER>.tls.domains[0].main=cc25.chasacademy.dev
        - traefik.http.routers.<DIN-HTTPS-ROUTER>.tls.domains[0].sans=*.cc25.chasacademy.dev
        - traefik.http.services.db-${STACK_NAME}.loadbalancer.server.port=8080
    environment:
      - ADMINER_DEFAULT_SERVER=rekurrens-db
    depends_on:
      - rekurrens-db

  rekurrens-db:
    image: registry.chasacademy.dev/chas-challenge-2025/group-12/rekurrens/mssql-db:${DOCKER_TAG}
    networks:
      - rekurrens-network
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - ACCEPT_EULA=YES
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true

networks:
  traefik-public:
    external: true
  rekurrens-network:
    internal: true
